version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    labels:
      - dependencies
    open-pull-requests-limit: 5

  - package-ecosystem: maven
    directory: /backend
    schedule:
      interval: weekly
    labels:
      - dependencies
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directories:
      - /backend
      - /frontend
    schedule:
      interval: weekly
    labels:
      - dependencies
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
    open-pull-requests-limit: 5
