ALTER TABLE store
    ADD COLUMN status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE store
    ADD COLUMN onboarding_completed BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE store
    ADD COLUMN archived_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE store
    ADD CONSTRAINT ck_store_status CHECK (status IN ('ACTIVE', 'ARCHIVED'));
