ALTER TABLE membership_invitation DROP CONSTRAINT ck_invitation_status;

ALTER TABLE membership_invitation ADD CONSTRAINT ck_invitation_status CHECK (status IN (
    'PENDING',
    'ACCEPTED',
    'DECLINED',
    'EXPIRED',
    'REVOKED'
));

ALTER TABLE audit_log DROP CONSTRAINT ck_audit_action;

ALTER TABLE audit_log ADD CONSTRAINT ck_audit_action CHECK (action IN (
    'STORE_CREATED',
    'STORE_ONBOARDING_COMPLETED',
    'STORE_UPDATED',
    'STORE_ARCHIVED',
    'STORE_REACTIVATED',
    'INVITATION_CREATED',
    'INVITATION_ACCEPTED',
    'INVITATION_DECLINED',
    'INVITATION_EXPIRED',
    'INVITATION_REVOKED',
    'MEMBER_ROLE_CHANGED',
    'MEMBER_REVOKED',
    'PRODUCT_CREATED',
    'PRODUCT_UPDATED',
    'PRODUCT_ARCHIVED',
    'PRODUCT_MEDIA_ATTACHED',
    'PRODUCT_PRIMARY_MEDIA_CHANGED',
    'PRODUCT_MEDIA_DELETED'
));
