package vn.omnismart.audit;

public enum AuditAction {
    STORE_CREATED,
    STORE_ONBOARDING_COMPLETED,
    STORE_UPDATED,
    STORE_ARCHIVED,
    STORE_REACTIVATED,
    INVITATION_CREATED,
    INVITATION_ACCEPTED,
    INVITATION_DECLINED,
    INVITATION_EXPIRED,
    INVITATION_REVOKED,
    MEMBER_ROLE_CHANGED,
    MEMBER_REVOKED,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_ARCHIVED,
    PRODUCT_MEDIA_ATTACHED,
    PRODUCT_PRIMARY_MEDIA_CHANGED,
    PRODUCT_MEDIA_DELETED,
    CONTENT_CREATED,
    CONTENT_VERSION_CREATED,
    CONTENT_SUBMITTED,
    CONTENT_APPROVED,
    CONTENT_REJECTED
}
